---
#- meta: end_play
#  when: (ansible_distribution != "CentOS" and ansible_distribution_major_version != "7")

- yum:
    name:
      - epel-release
      - zip
      - unzip
      - bzip2
      - wget
      - libselinux-python
      - policycoreutils-python
      - git
      - curl
      - yum-utils
      - mc
    state: present

- name: Change the hostname to our standard
  hostname:
      name: "{{ inventory_hostname }}"
  when:
      ansible_fqdn != ansible_host

- name: Build hosts file
  blockinfile:
      dest: /etc/cloud/templates/hosts.redhat.tmpl
      content: "{{ lookup('template', 'templates_etc_hosts.j2') }}"
      state: present

- name: Build hosts file2
  lineinfile:
     path:   /etc/cloud/templates/hosts.redhat.tmpl
     line:   "{{ hostvars[item].ansible_subnet2 }} {{ item }}"
     insertbefore: "{{ item }}"
  with_items:
     - "{{ groups['postgres'] }}"
     - "{{ groups['target'] }}"
     - "{{ groups['web_pcm'] }}"
